### ISSUE TITLE
Better document how to influence max decay

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer-docs#29] opened 2018-04-09 18:24 UTC

**Comment by shakuzen** [comment] 2024-01-30 07:23
https://github.com/micrometer-metrics/micrometer-docs/issues/66 seems to be a duplicate of this which was resolved with #101. If there are improvements to make, they should be opened as issues in the micrometer repo where the latest docs source is.

**Closed by shakuzen** 2024-01-30 07:23 UTC
