### ISSUE TITLE
Unclear multigauge documentation

### ISSUE THREAD

**Issue by michaldo** [micrometer-metrics/micrometer-docs#337] opened 2023-10-20 20:42 UTC
/main/src/docs/concepts/gauges.adoc

```
// run this periodically whenever you re-run your query
statuses.register(
    resultSet.stream()
        .map(result -> Row.of(Tags.of("status", result.getAsString("status")), result.getAsInt("count")))
        .collect(toList())
);
```
Something may be done **periodically**, something maybe done **whenever**. But is impossible do the same thing together **periodically** and **whenever**.

In my project mutligaude is implemented in **whenever** style and it degrades performance. Then I think it should be **periodically**, but I do not have confidence to make a PR

**Comment by jonatan-ivanov** [comment] 2023-10-23 23:50
I'm not sure I understand you. Could you please explain this with more details and using some examples?
When the docs says:
>// run this periodically whenever you re-run your query

It is not saying run it periodically OR whenever, there is no "periodical" or "whenever"  "style". What the docs says is update your Gauge every time you run your query, maybe we should rephrase it as:
>// run this every time when you re-run your query

If you want to interpret "periodical" as on a schedule using a scheduler and "whenever" as ad hoc (which I think you should not for the above sentence), I don't see why it would be impossible calling a method from a scheduler and ad-hoc too.

>In my project mutligaude is implemented in whenever style and it degrades performance. Then I think it should be periodically, but I do not have confidence to make a PR

I don't get what is the "whenever style" but if you see performance degradation caused by MultiGaguge, I don't think this issue should be here but against the main Micrometer repo.

>I do not have confidence to make a PR

What's the worst thing that can happen? :D We are here to help, if you want to open a PR but I guess opening an issue was a good idea to discuss what is the problem that you are facing.

I have one more idea what you could have meant "periodical" vs. "whenever":
`Gauge` is ~async so they will get "pulled"/updated when you publish the data (you update the state that the `Gauge` uses not the `Gauge` directly). `MultiGaguge` on the other hand is ~synchronous so you will update it directly. Does it make sense so far?

`MultiGauge` is basically creating a bunch of `Gauge`s for you and it tracks their state, it is a convenient way if you want to create many `Gauge`s. But you can do that on your own too:

```java
// in the ctor
AtomicInteger lastSuccessStatusCount = registry.gauge("numberGauge", "status", "SUCCESS", new AtomicInteger(0));
AtomicInteger lastFailureStatusCount = registry.gauge("numberGauge", "status", "FAILURE", new AtomicInteger(0));
AtomicInteger lastUnknownStatusCount = registry.gauge("numberGauge", "status", "UNKNOWN", new AtomicInteger(0));

// then every time you run your query:
for (Result result : resultSet) {
    String status = result.getAsString("status");
    int count = result.getAsInt("count");
    switch(status) {
      case "SUCCESS":
        lastSuccessStatusCount.set(count);
        break;
      case "FAILURE":
        lastFailureStatusCount.set(count);
        break;
      default:
        lastUnknownStatusCount.set(count);
    }
}
```

This is somewhat similar to what the `MultiGauge` example does except it is automatically handle other statuses as well, not just 2 (3).

**Comment by michaldo** [comment] 2023-10-24 09:55
I want manage growing or shrinking list if gauges. 
For example :

| second  | gauges|
| ------------- | ------------- |
| 1  | success: 10, failure: 5  |
| 3  | unknown: 4|
| 7 | success: 7, unknown:3  |

Numbers and gauges list changes very often -  10 times per second
How often should MultiGauge should be updated by `multigauge.register()` ? Periodically, for example once per 10 seconds or whenever state changes, for example 10 times per second? Which form of MultiGauge.Row should I use: fixed with static value or dynamic?

I think now, problem is that MultiGauge mixes 2 usage pattern. 
First pattern is "state-snapshot", with fixed MultiGauge.Row (Tag, Number) and second pattern is "gauge-starter", with dynamic MultiGauge.Row (Tag, Object, ToDoubleFunction).

I need more time to analyze this concept, but at first look both pattern have a design problems:
"State-snapshot" is something natural, but implementation should update state as a whole, not row by row. Additionally, documentation should recommend update state snapshot periodically. Additionally, new snapshot should always replace old snapshot.
"Gauge-starter" is also natural: there is a list of gauges, some new may appear, some old should be dropped. But it does not have a sense `overwrite` parameter. Additionally, gauges should not be created and dropped very frequently. Gauges should live some time - if they born and die very often, better use "state-snapshot"

To conclude, I think now that problem is not in documentation, but in design. On one hand, there is reasonable concept that:

> Attempting to construct a gauge with a primitive number or one of its java.lang object forms is always incorrect. These numbers are immutable. Thus, the gauge cannot ever be changed. 

On the second there, there is a MutliGauge designed to create multiple gauges breaking the reasonable concept above with `Row.of(Tag, Number)`

**Comment by jonatan-ivanov** [comment] 2023-10-25 00:10
>I want manage growing or shrinking list if gauges.

This is not a good idea, you should not remove meters once they are registered. There is a difference between publishing zero value and missing value.
With this, your example would look like this:

second | gauges
-- | --
1 | `success: 10`, `failure: 5`, `unknown: 0`
3 | `success:  0`, `failure: 0`, `unknown: 4`
7 | `success:  7`, `failure: 0`, `unknown: 3`


>Numbers and gauges list changes very often - 10 times per second
How often should MultiGauge should be updated by multigauge.register() ? Periodically, for example once per 10 seconds or whenever state changes, for example 10 times per second?

It depends. :) In general, you should update the value/state of the gauge every time whenever state changes. The Gauge will only fetch this value when the Gauge is "pulled", i.e.: when the data is published (by default once per minute for step meters and once per scrape for Prometheus).
If this is too expensive, you should cache the values (update the cache less frequently) and query the cache from the Gauge (though in your case, updating an `AtomicXyz` should not be very expensive).

>Which form of MultiGauge.Row should I use: fixed with static value or dynamic?

It depends. :) If you have dynamic values, then you should create the tags dynamically, if only static, you can use one static `Tags` instance. Btw you can also have one static instance and create others from that dynamically:
```java
private static final Tags STATIC_TAGS = Tags.of("magic", 42);
// ...
Tags staticWithDynamic = STATIC_TAGS.and("status", result.getAsString("status"));
```

**Comment by michaldo** [comment] 2023-10-25 23:10
> > I want manage growing or shrinking list if gauges.
> 
> This is not a good idea, you should not remove meters once they are registered. 

Maybe that is not good idea, but according to doc,

`special type of Gauge, called a MultiGauge, to help manage gauging a growing or shrinking list of criteria`


> There is a difference between publishing zero value and missing value. 

Exactly, in my case, if I have missing value, I do not want publish metric 0 but I want do not publish metric at all.

I think now that primary goal for MultiGauge is periodical query for fixed numbers and update the multi gauge according to numbers. Exactly like in current documentation, the only missing part is clear comment 
`// run this periodically, with the same frequency as scraping frequency`

Although MultiGauge may register and deregister "true", changing gauges (like atomic integer), I'm not convinced MultiGauge is best solution for that and ability of registering real gauges can be left undocumented.

**Comment by jonatan-ivanov** [comment] 2023-10-25 23:47
>Maybe that is not good idea, but according to doc,
>special type of Gauge, called a MultiGauge, to help manage gauging a growing or shrinking list of criteria

Please use a `MultiGauge` in that case, fyi: it will do the same I explained above and it will not remove `Gauge`s. Please try it out, `MultiGauge` is "just" a helper to create many gauges without the need of maintaining their state.

>Exactly, in my case, if I have missing value, I do not want publish metric 0 but I want do not publish metric at all.

Not publishing it means your app is down or not able to report the data, if you want to signal that you can remove the gauge from the registry but I would highly recommend against it.

**Comment by michaldo** [comment] 2023-10-26 06:40
The documentation has example with static MultiGauge powered by SQL query. Could you provide snippet of code how to use MultiGauge to register true gauges powered by AtomicInteger?

> Not publishing it (gauge) means your app is down or not able to report the data, if you want to signal that you can remove the gauge from the registry but I would highly recommend against it.

I understand that gauges are designed for frequent register/deregister. But how to implement gauge for sensor temperature? If sensor is not able to report the data, it does not mean that temperature is 0 C degree.

**Comment by jonatan-ivanov** [comment] 2023-10-26 16:14
>The documentation has example with static MultiGauge powered by SQL query. Could you provide snippet of code how to use MultiGauge to register true gauges powered by AtomicInteger?

Look into the source code of MultiGauge, the example does that (registering true `Gauge`s). It will use double under the hood, but the input value is integer in the docs: `result.getAsInt("count")`

Here's an other example that registers a bunch of `Gauge`s using simply `Gauge` (keeping the values in a `Map`) and does the exact same thing using a `MultiGauge`: https://github.com/micrometer-metrics/micrometer/issues/3826#issuecomment-1542722684

>I understand that gauges are designed for frequent register/deregister.

That's not a good understanding. Meters (including `Gauge`) should not be frequently de/re-registered. You can change the value of its state as frequently as you want but hat is very different from being de/re-registered.

>But how to implement gauge for sensor temperature? If sensor is not able to report the data, it does not mean that temperature is 0 C degree.

Let me call out here that up to this point I thought we were talking about the number of something (count) where zero can be a completely valid value if that thing is missing or you are unable to fetch. The temp sensor example is a little different that that. If you are not able to fetch the data from the sensor, I'm not sure why you want to report `0` or any other arbitrary valid value. In that case you can just report `null` from the code that fetches the data and the Gauge will report `NaN`:

```java
PrometheusMeterRegistry registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
Gauge.builder("temp", () -> null)
    .baseUnit("celsius")
    .register(registry);
System.out.println(registry.scrape());
```
which will produce this:
```
# HELP temp_celsius  
# TYPE temp_celsius gauge
temp_celsius NaN
```

**Comment by michaldo** [comment] 2023-10-27 20:55
Hi, 
I obviously wanted to write:

> I understand that gauges are **NOT** designed for frequent register/deregister.

But it is not very important, because your answer with temperature sensor is clear.

Summary:
Let's name _static gauge_ (SG) gauge with fixed value and _dynamic gauge_ (DG) gauge with changing value. SG, as written in doc, is antipattern.
DG are not designed to (frequent) register/deregister - it is next antipattern.

There is a natural need to report state of system basing on SQL query or something like this. Convenient realization of this need is MultiGauge + SG. It use SG anti pattern, it use deregister anti pattern - but is simple, it works and it does not hurt performance when runs periodically - and periodical run is enough. Enough for scrapping.

Unfortunately, MultiGauge has second nature - it may also be used to register DG.  It breaks single responsibility principle, it encourage to deregister antipattern, and I doubt it is very useful - _you referred example how to use MultiGauge with random values, not use case for MultiGauge with DG_.

Regardless breaking single responsibility, which is a bit fuzzy, the MultiGauge API is badly designed. I mean it is possible to register SG with overwrite=false - it does not have a sense.  It is also possible to register DG with overwrite=true: i do not see an use case for that. I can imagine that I can add DG, but not replace DG

I created #339 to clarify SQL query example and I left MultiGauge design review for authors

**Comment by jonatan-ivanov** [comment] 2024-01-25 22:22
Closed by https://github.com/micrometer-metrics/micrometer-docs/pull/339

**Closed by jonatan-ivanov** 2024-01-25 22:22 UTC
Labels: feedback needed
